name: Presto
on:
  push:
    branches:
      - antithesis
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  pull_request:
    branches:
      - antithesis
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
jobs:
  presto:
    name: DBMS Tests (Presto)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Set up Presto
        run: |
          docker pull prestodb/presto:latest
          echo "connector.name=memory" >> memory.properties
          docker run -p 8080:8080 -d -v ./memory.properties:/opt/presto-server/etc/catalog/memory.properties --name presto prestodb/presto:latest
          until curl -sf http://127.0.0.1:8080/v1/info 2>/dev/null; do sleep 2; done
      - name: Build SQLancer
        run: mvn -B package -DskipTests=true
      - name: Run Tests
        run: |
          PRESTO_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestPrestoNoREC test
          docker restart presto && until curl -sf http://127.0.0.1:8080/v1/info 2>/dev/null; do sleep 2; done
          PRESTO_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestPrestoTLP test
