name: YugabyteDB
on:
  push:
    branches:
      - antithesis
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
  pull_request:
    branches:
      - antithesis
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yml'
      - 'pom.xml'
jobs:
  yugabyte:
    name: DBMS Tests (YugabyteDB)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build SQLancer
        run: mvn -B package -DskipTests=true
      - name: Set up Yugabyte
        run: |
          docker pull yugabytedb/yugabyte:latest
          docker run -d --name yugabyte -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 yugabytedb/yugabyte:latest bin/yugabyted start --daemon=false --tserver_flags="ysql_yb_enable_listen_notify=true" --master_flags="ysql_yb_enable_listen_notify=true"
          until pg_isready -h localhost -p 5433; do sleep 1; done
          until nc -z localhost 9042; do sleep 1; done
      - name: Run Tests
        run: |
          YUGABYTE_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestYSQLNoREC test
          YUGABYTE_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestYSQLTLP test
          YUGABYTE_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestYSQLPQS test
          YUGABYTE_AVAILABLE=true mvn -Djacoco.skip=true -Dtest=TestYCQL test
